#ifndef CORE_MODELID_HPP
#define CORE_MODELID_HPP

enum class ModelID {
    CAR__PORSCHE_911_CARRERA_993,
    CAR__DODGE_CHARGER_RT_1969,
    CAR__HORAI_BX300_1996,
    
    ENV__SNOW_MOUNTAINS,

    TRK__CIRCUIT8_BRIDGE,

    COUNT
};

#endif